default:
	@cd Mode1 && make
	@cd Mode5 && make
	@cd Mode8 && make
	@cd Mode9 && make

install:
	@cd Mode1 && make install
	@cd Mode5 && make install
	@cd Mode8 && make install
	@cd Mode9 && make install

uninstall:
	@cd Mode1 && make uninstall
	@cd Mode5 && make uninstall
	@cd Mode8 && make uninstall
	@cd Mode9 && make uninstall

clean:
	@cd Mode1 && make clean
	@cd Mode5 && make clean
	@cd Mode8 && make clean
	@cd Mode9 && make clean
	