default:
	@cd TestMode0Debug && make
	@cd TestMode1 && make
	@cd TestMode2 && make
	@cd TestMode4 && make
	@cd TestMode5 && make
	@cd TestMode8 && make
	@cd TestMode9 && make

install:
	@cd TestMode0Debug && make install
	@cd TestMode1 && make install
	@cd TestMode2 && make install
	@cd TestMode4 && make install
	@cd TestMode5 && make install
	@cd TestMode8 && make install
	@cd TestMode9 && make install

uninstall:
	@cd TestMode0Debug && make uninstall
	@cd TestMode1 && make uninstall
	@cd TestMode2 && make uninstall
	@cd TestMode4 && make uninstall
	@cd TestMode5 && make uninstall
	@cd TestMode8 && make uninstall
	@cd TestMode9 && make uninstall

clean:
	@cd TestMode0Debug && make clean
	@cd TestMode1 && make clean
	@cd TestMode2 && make clean
	@cd TestMode4 && make clean
	@cd TestMode5 && make clean
	@cd TestMode8 && make clean
	@cd TestMode9 && make clean
	